### ISSUE TITLE
RuntimeError: cuda runtime error

### ISSUE THREAD

**Issue by YANYANYEAH** [leftthomas/SRGAN#10]
[converting LR images to SR images] PSNR: 20.9384 dB SSIM: 0.5722:   1%| | 1/176[converting LR images to SR images] PSNR: 20.4518 dB SSIM: 0.5069:   1%| | 2/176[converting LR images to SR images] PSNR: 21.5431 dB SSIM: 0.5412:   2%| | 3/176[converting LR images to SR images] PSNR: 22.1938 dB SSIM: 0.5864:   2%| | 4/176[converting LR images to SR images] PSNR: 21.0993 dB SSIM: 0.5593:   3%| | 5/176 [00:00<00:34,  5.00it/s]THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1501972792122/work/pytorch-0.1.12/torch/lib/THC/generic/THCStorage.cu line=66 error=2 : out of memory
Traceback (most recent call last):
  File "train.py", line 119, in <module>
    sr = netG(lr)
  File "/home/zbp/anaconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 206, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zbp/linge/SRGAN/model.py", line 37, in forward
    block8 = self.block8(block1 + block7)
  File "/home/zbp/anaconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 206, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zbp/anaconda2/lib/python2.7/site-packages/torch/nn/modules/container.py", line 64, in forward
    input = module(input)
  File "/home/zbp/anaconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 206, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zbp/anaconda2/lib/python2.7/site-packages/torch/nn/modules/conv.py", line 237, in forward
    self.padding, self.dilation, self.groups)
  File "/home/zbp/anaconda2/lib/python2.7/site-packages/torch/nn/functional.py", line 40, in conv2d
    return f(input, weight, bias)
RuntimeError: cuda runtime error (2) : out of memory at /opt/conda/conda-bld/pytorch_1501972792122/work/pytorch-0.1.12/torch/lib/THC/generic/THCStorage.cu:66

Thanks for your nice code,but I have some issues about runtime error when training.Can you help me to solve this problem?

**Comment by leftthomas** [comment]
@YANYANYEAH firstly, you should make sure your gpu have more than 8g. Then make sure you use pytorch 0.3.1, finally, you crop the image should less than 96*96
