### ISSUE TITLE
Error when train with new dataset

### ISSUE THREAD

**Issue by damvantai** [leftthomas/SRGAN#17]
after terminal python train.py, appear error below, i don't find error ? Can you help me? thank you!
`/usr/lib/python3/dist-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.23) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
# generator parameters: 734092
# discriminator parameters: 5215425
  0%|                                                     | 0/1 [00:00<?, ?it/s]Traceback (most recent call last):
  File "train.py", line 60, in <module>
    for data, target in train_bar:
  File "/home/neosai/.local/lib/python3.6/site-packages/tqdm/_tqdm.py", line 930, in __iter__
    for obj in iterable:
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 336, in __next__
    return self._process_next_batch(batch)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 357, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
ValueError: Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 106, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 106, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/neosai/Documents/github/GAN/SRGAN/data_utils.py", line 50, in __getitem__
    hr_image = self.hr_transform(Image.open(self.image_filenames[index]))
  File "/usr/local/lib/python3.6/dist-packages/torchvision/transforms/transforms.py", line 49, in __call__
    img = t(img)
  File "/usr/local/lib/python3.6/dist-packages/torchvision/transforms/transforms.py", line 421, in __call__
    i, j, h, w = self.get_params(img, self.size)
  File "/usr/local/lib/python3.6/dist-packages/torchvision/transforms/transforms.py", line 399, in get_params
`

**Comment by leftthomas** [comment]
@damvantai install the libs as `Requirements` said, and you should use PyTorch 0.3.1 and Python 3.6
