### ISSUE TITLE
error when trying to run the code

### ISSUE THREAD

**Issue by Jerchongkong** [leftthomas/SRGAN#39]
When I try to do anything, whether it is scaling an image, video or whatever, this error always comes out:

Traceback (most recent call last):
  File "test_video.py", line 30, in <module>
    model.load_state_dict(torch.load('epochs/' + MODEL_NAME))
  File "/usr/local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 522, in load_state_dict
    .format(name))
KeyError: 'unexpected key "block8.1.weight" in state_dict'

or:

Traceback (most recent call last):
  File "test_video.py", line 30, in <module>
    model.load_state_dict(torch.load('epochs/' + MODEL_NAME))
  File "/usr/local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 526, in load_state_dict
    raise KeyError('missing keys in state_dict: "{}"'.format(missing))
KeyError: 'missing keys in state_dict: "{\'block7.1.running_var\', \'block7.1.bias\', \'block7.1.running_mean\'}"'

I use ubuntu 18.04, pytorch 0.3.1 and cuda 9

**Comment by leftthomas** [comment]
@Jerchongkong The model has been modified, so the pretrained weight is wrong, you need train by yourself
