### ISSUE TITLE
RuntimeError: 

### ISSUE THREAD

**Issue by leiyaohui** [leftthomas/SRGAN#47]
hello!
When I run the program, I encounter the following errors. I hope you can give me an answer.Thanks!

RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

**Comment by leftthomas** [comment]
@leiyaohui are you sure this is my code？

**Comment by Dreamkeeper66666** [comment]
Hi, I also had the same problem! @leftthomas

**Comment by Dreamkeeper66666** [comment]
`# generator parameters: 734219
# discriminator parameters: 5215425
  0%|                                                                                                                   | 0/125 [00:00<?, ?it/s]# generator parameters: 734219
# discriminator parameters: 5215425
  0%|                                                                                                                   | 0/125 [00:00<?, ?it/s]Traceback (most recent call last):
  File "<string>", line 1, in <module>
Traceback (most recent call last):
  File "train.py", line 61, in <module>
  File "D:\Anaconda3\envs\torch\lib\multiprocessing\spawn.py", line 105, in spawn_main
    for data, target in train_bar:
  File "D:\Anaconda3\envs\torch\lib\site-packages\tqdm\std.py", line 1081, in __iter__
    exitcode = _main(fd)
  File "D:\Anaconda3\envs\torch\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "D:\Anaconda3\envs\torch\lib\multiprocessing\spawn.py", line 225, in prepare
    for obj in iterable:
  File "D:\Anaconda3\envs\torch\lib\site-packages\torch\utils\data\dataloader.py", line 278, in __iter__
    _fixup_main_from_path(data['init_main_from_path'])
  File "D:\Anaconda3\envs\torch\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    return _MultiProcessingDataLoaderIter(self)
  File "D:\Anaconda3\envs\torch\lib\site-packages\torch\utils\data\dataloader.py", line 682, in __init__
    run_name="__mp_main__")
  File "D:\Anaconda3\envs\torch\lib\runpy.py", line 263, in run_path
    w.start()
    pkg_name=pkg_name, script_name=fname)
  File "D:\Anaconda3\envs\torch\lib\runpy.py", line 96, in _run_module_code
  File "D:\Anaconda3\envs\torch\lib\multiprocessing\process.py", line 112, in start
    mod_name, mod_spec, pkg_name, script_name)
  File "D:\Anaconda3\envs\torch\lib\runpy.py", line 85, in _run_code
    self._popen = self._Popen(self)
  File "D:\Anaconda3\envs\torch\lib\multiprocessing\context.py", line 223, in _Popen
    exec(code, run_globals)
  File "C:\Users\Admin\Desktop\SRGAN-torch\train.py", line 61, in <module>
    return _default_context.get_context().Process._Popen(process_obj)
  File "D:\Anaconda3\envs\torch\lib\multiprocessing\context.py", line 322, in _Popen
    for data, target in train_bar:
  File "D:\Anaconda3\envs\torch\lib\site-packages\tqdm\std.py", line 1081, in __iter__
    return Popen(process_obj)
  File "D:\Anaconda3\envs\torch\lib\multiprocessing\popen_spawn_win32.py", line 89, in __init__
    reduction.dump(process_obj, to_child)
  File "D:\Anaconda3\envs\torch\lib\multiprocessing\reduction.py", line 60, in dump
    for obj in iterable:
  File "D:\Anaconda3\envs\torch\lib\site-packages\torch\utils\data\dataloader.py", line 278, in __iter__
    ForkingPickler(file, protocol).dump(obj)
BrokenPipeError: [Errno 32] Broken pipe
    return _MultiProcessingDataLoaderIter(self)
  File "D:\Anaconda3\envs\torch\lib\site-packages\torch\utils\data\dataloader.py", line 682, in __init__
    w.start()
  File "D:\Anaconda3\envs\torch\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "D:\Anaconda3\envs\torch\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "D:\Anaconda3\envs\torch\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "D:\Anaconda3\envs\torch\lib\multiprocessing\popen_spawn_win32.py", line 46, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "D:\Anaconda3\envs\torch\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File "D:\Anaconda3\envs\torch\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
  0%|                                                                                                                   | 0/125 [00:03<?, ?it/s]
  0%|                                                                                                                   | 0/125 [00:00<?, ?it/s]`
