### ISSUE TITLE
Problem when running train.py

### ISSUE THREAD

**Issue by XuZikang** [leftthomas/SRGAN#59]
Hi, I run your code train.py on Ubuntu 16.04 with 16G memory and 3G swap, but it always occurs bug after finishing one epoch. Could you tell me how to fix it? Thank you very much!

Here is the error code:
[1/100] Loss_D: 0.9897 Loss_G: 0.0133 D(x): 0.5404 D(G(z)): 0.5272: 100%|██████████| 522/522 [02:10<00:00,  4.43it/s]
[converting LR images to SR images] PSNR: 22.6254 dB SSIM: 0.6516: 100%|██████████| 425/425 [00:34<00:00, 12.31it/s]
[saving training results]: 100%|██████████| 85/85 [01:44<00:00,  1.21s/it]
  0%|          | 0/522 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/home/terrypang/康康/SRGAN-master/train.py", line 60, in <module>
    for data, target in train_bar:
  File "/usr/local/lib/python3.6/dist-packages/tqdm/_tqdm.py", line 979, in __iter__
    for obj in iterable:
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 193, in __iter__
    return _DataLoaderIter(self)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 469, in __init__
    w.start()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/usr/lib/python3.6/multiprocessing/context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/usr/lib/python3.6/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/usr/lib/python3.6/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/lib/python3.6/multiprocessing/popen_fork.py", line 66, in _launch
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory

**Comment by jinzhenmu** [comment]
这个原因，有可能是电脑配置不够，内存分配不够了。还有可能是数据集太大了，换成分辨率低一点的数据集试试。
