### ISSUE TITLE
Test Scripts Not Working

### ISSUE THREAD

**Issue by rizasif** [leftthomas/SRGAN#6]
Hi,

I ran the video test scripts and it completed successfully. However, I could not find the output videos anywhere on my system. Here is the output.
```
turanshare@deepNeuro:~/Documents/github/dev/SRGAN$ python test_video.py --video_name "/home/turanshare/Documents/github/dev/SRGAN/sample.mp4"
[processing video and saving result videos]: 100%|██████████████████████████████████████████████████████████████████████████████████| 2003/2003 [28:00<00:00,  1.19it/s]
```

Moreover, when I run the image test it fails with an 'out of memory' error. I am not sure why is this happening.
```
turanshare@deepNeuro:~/Documents/github/dev/SRGAN$ python test_image.py --image_name "/home/turanshare/Documents/github/dev/SRGAN/riz.jpg"
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1518238409320/work/torch/lib/THC/generic/THCStorage.cu line=58 error=2 : out of memory
*** Error in `python': free(): invalid pointer: 0x00007f273ba24ec0 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x777e5)[0x7f27549a87e5]
/lib/x86_64-linux-gnu/libc.so.6(+0x8037a)[0x7f27549b137a]
/lib/x86_64-linux-gnu/libc.so.6(cfree+0x4c)[0x7f27549b553c]
/home/turanshare/anaconda2/lib/python2.7/site-packages/torch/_thnn/_THCUNN.so(+0x34cb9)[0x7f26f8624cb9]
/home/turanshare/anaconda2/bin/../lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x79e5)[0x7f275570a615]
/home/turanshare/anaconda2/bin/../lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7e9)[0x7f275570c4e9]
/home/turanshare/anaconda2/bin/../lib/libpython2.7.so.1.0(+0x6cfda)[0x7f2755694fda]
/home/turanshare/anaconda2/bin/../lib/libpython2.7.so.1.0(PyObject_Call+0x43)[0x7f2755670773]
/home/turanshare/anaconda2/bin/../lib/libpython2.7.so.1.0(PyEval_CallObjectWithKeywords+0x48)[0x7f27557026d8]
/home/turanshare/anaconda2/lib/python2.7/site-packages/torch/_C.so(_Z17THPFunction_applyP7_objectS0_+0x271)[0x7f273a4a4201]
/home/turanshare/anaconda2/bin/../lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x79e5)[0x7f275570a615]
/home/turanshare/anaconda2/bin/../lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x817c)[0x7f275570adac]
/home/turanshare/anaconda2/bin/../lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7e9)[0x7f275570c4e9]
/home/turanshare/anaconda2/bin/../lib/libpython2.7.so.1.0(+0x6d0c7)[0x7f27556950c7]
/home/turanshare/anaconda2/bin/../lib/libpython2.7.so.1.0(PyObject_Call+0x43)[0x7f2755670773]
/home/turanshare/anaconda2/bin/../lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x28a0)[0x7f27557054d0]
/home/turanshare/anaconda2/bin/../lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7e9)[0x7f275570c4e9]
/home/turanshare/anaconda2/bin/../lib/libpython2.7.so.1.0(+0x6cfda)[0x7f2755694fda]
/home/turanshare/anaconda2/bin/../lib/libpython2.7.so.1.0(PyObject_Call+0x43)[0x7f2755670773]
/home/turanshare/anaconda2/bin/../lib/libpython2.7.so.1.0(+0x5750d)[0x7f275567f50d]
/home/turanshare/anaconda2/bin/../lib/libpython2.7.so.1.0(PyObject_Call+0x43)[0x7f2755670773]
/home/turanshare/anaconda2/bin/../lib/libpython2.7.so.1.0(+0xa1574)[0x7f27556c9574]
/home/turanshare/anaconda2/bin/../lib/libpython2.7.so.1.0(PyObject_Call+0x43)[0x7f2755670773]
/home/turanshare/anaconda2/bin/../lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x190b)[0x7f275570453b]
/home/turanshare/anaconda2/bin/../lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7e9)[0x7f275570c4e9]
/home/turanshare/anaconda2/bin/../lib/libpython2.7.so.1.0(+0x6d0c7)[0x7f27556950c7]
/home/turanshare/anaconda2/bin/../lib/libpython2.7.so.1.0(PyObject_Call+0x43)[0x7f2755670773]
/home/turanshare/anaconda2/bin/../lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x28a0)[0x7f27557054d0]
/home/turanshare/anaconda2/bin/../lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7e9)[0x7f275570c4e9]
/home/turanshare/anaconda2/bin/../lib/libpython2.7.so.1.0(+0x6cfda)[0x7f2755694fda]
/home/turanshare/anaconda2/bin/../lib/libpython2.7.so.1.0(PyObject_Call+0x43)[0x7f2755670773]
/home/turanshare/anaconda2/bin/../lib/libpython2.7.so.1.0(+0x5750d)[0x7f275567f50d]
/home/turanshare/anaconda2/bin/../lib/libpython2.7.so.1.0(PyObject_Call+0x43)[0x7f2755670773]
/home/turanshare/anaconda2/bin/../lib/libpython2.7.so.1.0(+0xa1574)[0x7f27556c9574]
/home/turanshare/anaconda2/bin/../lib/libpython2.7.so.1.0(PyObject_Call+0x43)[0x7f2755670773]
/home/turanshare/anaconda2/bin/../lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x190b)[0x7f275570453b]
/home/turanshare/anaconda2/bin/../lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7e9)[0x7f275570c4e9]
/home/turanshare/anaconda2/bin/../lib/libpython2.7.so.1.0(+0x6d0c7)[0x7f27556950c7]
/home/turanshare/anaconda2/bin/../lib/libpython2.7.so.1.0(PyObject_Call+0x43)[0x7f2755670773]
/home/turanshare/anaconda2/bin/../lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x28a0)[0x7f27557054d0]
/home/turanshare/anaconda2/bin/../lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7e9)[0x7f275570c4e9]
/home/turanshare/anaconda2/bin/../lib/libpython2.7.so.1.0(+0x6cfda)[0x7f2755694fda]
/home/turanshare/anaconda2/bin/../lib/libpython2.7.so.1.0(PyObject_Call+0x43)[0x7f2755670773]
/home/turanshare/anaconda2/bin/../lib/libpython2.7.so.1.0(+0x5750d)[0x7f275567f50d]
/home/turanshare/anaconda2/bin/../lib/libpython2.7.so.1.0(PyObject_Call+0x43)[0x7f2755670773]
/home/turanshare/anaconda2/bin/../lib/libpython2.7.so.1.0(+0xa1574)[0x7f27556c9574]
/home/turanshare/anaconda2/bin/../lib/libpython2.7.so.1.0(PyObject_Call+0x43)[0x7f2755670773]
/home/turanshare/anaconda2/bin/../lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x190b)[0x7f275570453b]
/home/turanshare/anaconda2/bin/../lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7e9)[0x7f275570c4e9]
/home/turanshare/anaconda2/bin/../lib/libpython2.7.so.1.0(PyEval_EvalCode+0x1a)[0x7f275570c70a]
/home/turanshare/anaconda2/bin/../lib/libpython2.7.so.1.0(+0xfd93d)[0x7f275572593d]
/home/turanshare/anaconda2/bin/../lib/libpython2.7.so.1.0(PyRun_FileExFlags+0x78)[0x7f2755726ab8]
/home/turanshare/anaconda2/bin/../lib/libpython2.7.so.1.0(PyRun_SimpleFileExFlags+0xe8)[0x7f2755727cd8]
/home/turanshare/anaconda2/bin/../lib/libpython2.7.so.1.0(Py_Main+0xbac)[0x7f2755739d3c]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0)[0x7f2754951830]
python(+0x87f)[0x5598ccb0a87f]
======= Memory map: ========
10000000-10001000 rw-s 00000000 00:06 519                                /dev/nvidia3
10001000-10002000 rw-s 00000000 00:06 519                                /dev/nvidia3
10002000-10003000 rw-s 00000000 00:06 519                                /dev/nvidia3
10003000-10004000 rw-s 00000000 00:06 519                                /dev/nvidia3
10004000-10005000 rw-s 00000000 00:06 519                                /dev/nvidia3
10005000-10006000 rw-s 00000000 00:06 519                                /dev/nvidia3
10006000-10007000 rw-s 00000000 00:06 519                                /dev/nvidia3
10007000-10008000 rw-s 00000000 00:06 519                                /dev/nvidia3
10008000-10009000 rw-s 00000000 00:06 519                                /dev/nvidia3
10009000-1000a000 rw-s 00000000 00:06 519                                /dev/nvidia3
1000a000-1000b000 rw-s 00000000 00:06 519                                /dev/nvidia3
1000b000-1000c000 rw-s 00000000 00:06 519                                /dev/nvidia3
1000c000-1000d000 rw-s 00000000 00:06 519                                /dev/nvidia3
1000d000-1000e000 rw-s 00000000 00:06 519                                /dev/nvidia3
1000e000-1000f000 rw-s 00000000 00:06 519                                /dev/nvidia3
1000f000-10010000 rw-s 00000000 00:06 519                                /dev/nvidia3
10010000-20000000 ---p 00000000 00:00 0
200000000-200100000 rw-s 00000000 00:06 518                              /dev/nvidiactl
200100000-200200000 ---p 00000000 00:00 0
200200000-200204000 rw-s 00000000 00:06 518                              /dev/nvidiactl
200204000-200400000 ---p 00000000 00:00 0
200400000-200800000 rw-s 00000000 00:06 518                              /dev/nvidiactl
.
.
.
7f27474f4000-7f27474f5000 r--p 00010000 fc:00 464971                     /home/turanshare/anaconda2/lib/libgcc_s.so.1
7f27474f5000-7f27474f6000 rw-p 00011000 fc:00 464971                     /home/turanshare/anaconda2/lib/libgcc_s.so.1Aborted (core dumped)
```

Kindly, if anyone can help me with this.
Thank you.

**Comment by leftthomas** [comment]
First, you should put your test videos and test images on the project root directory, not other directories, then after you run the test scripts, the results will generated on the project root directory, you’ll know why this happened if you have seen my code.
Secondly, I recommend you to use Python 3 version, my code is written by Python 3, the Python 3 version PyTorch behaves differently with Python 2 version. I haven’t test it on Python 2.

**Comment by rizasif** [comment]
That worked, thank you.

**Comment by rizasif** [comment]
The video test works, however, image test is still going out of memory, despite being on the same machine. Here are the logs on Python3 and image on root directory.
```
$ python test_image.py --image_name "riz.jpg"
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1518243271935/work/torch/lib/THC/generic/THCStorage.cu line=58 error=2 : out of memory
Traceback (most recent call last):
  File "test_image.py", line 37, in <module>
    out = model(image)
  File "/home/turanshare/anaconda2/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/turanshare/Documents/github/dev/SRGAN/model.py", line 37, in forward
    block8 = self.block8(block1 + block7)
  File "/home/turanshare/anaconda2/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/turanshare/anaconda2/envs/py36/lib/python3.6/site-packages/torch/nn/modules/container.py", line 67, in forward
    input = module(input)
  File "/home/turanshare/anaconda2/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/turanshare/Documents/github/dev/SRGAN/model.py", line 116, in forward
    x = self.pixel_shuffle(x)
  File "/home/turanshare/anaconda2/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/turanshare/anaconda2/envs/py36/lib/python3.6/site-packages/torch/nn/modules/pixelshuffle.py", line 40, in forward
    return F.pixel_shuffle(input, self.upscale_factor)
  File "/home/turanshare/anaconda2/envs/py36/lib/python3.6/site-packages/torch/nn/functional.py", line 1372, in pixel_shuffle
    shuffle_out = input_view.permute(0, 1, 4, 2, 5, 3).contiguous()
  File "/home/turanshare/anaconda2/envs/py36/lib/python3.6/site-packages/torch/autograd/variable.py", line 280, in contiguous
    self.data = self.data.contiguous()
RuntimeError: cuda runtime error (2) : out of memory at /opt/conda/conda-bld/pytorch_1518243271935/work/torch/lib/THC/generic/THCStorage.cu:58
```

**Comment by leftthomas** [comment]
@rizasif how's the resolution of your test image-'riz.jpg'? And how's the memory of your GPU?

**Comment by rizasif** [comment]
It is a 1760x2024 image with 96dpi resolution. You can find the image and video, I am using, in the development branch of the forked repository [here](https://github.com/rizasif/SRGAN).

I am using an NVIDIA GTX 1050 .

**Comment by leftthomas** [comment]
NVIDIA GTX 1050 only have 2GB memory, and your test image is 1760x2024 RGB data, it is a huge data! Of course it will got OOM error... , you could compute how many memories the network will use by yourself.

**Comment by rizasif** [comment]
Okay, I'll give it a shot on a smaller video

**Comment by rizasif** [comment]
It worked. Thank you.
