### ISSUE TITLE
What is the version of pytorch and torchvision?

### ISSUE THREAD

**Issue by kuroyanagi33** [leftthomas/SRGAN#9]
Could you tell me the versions of pytorch and torchvision? The following error has occurred.

```
⋊> ~/SRGAN on master ⨯   python train.py                                                                                                 0909:00:51
Traceback (most recent call last):
  File "train.py", line 14, in <module>
    from data_utils import TrainDatasetFromFolder, ValDatasetFromFolder, display_transform
  File "/root/SRGAN/data_utils.py", line 6, in <module>
    from torchvision.transforms import Compose, RandomCrop, ToTensor, ToPILImage, CenterCrop, Resize
ImportError: cannot import name 'Resize'
⋊> ~/SRGAN on master ⨯
```

**Comment by handsome-to** [comment]
the same question
require help either
pl.

**Comment by handsome-to** [comment]
i have resolved that 
 thanks
